### ISSUE TITLE
I'm having an issue trying to swap a token to ADA on all DEXs

### ISSUE THREAD

**Issue by catad83** [IndigoProtocol/dexter#67]
### Data Provider

Custom

### DEX

All

### Description

Trying to play with Dexter a bit ans can't figure this out, getting an error when trying to swap a token... can't figure it out what I'm doing wrong. I'm able to swap 'lovelace' to token but a token to 'lovelace' gives me this error, no matter the DEX.

var sellSwap: SwapRequest   = dexter.newSwapRequest()
							.forLiquidityPool( outPool )
							.withSwapInToken( _token )
							.withSwapInAmount( _tokenAmount ) 
							.withSlippagePercent(5);
									
submitSellTx = sellSwap.submit();

file:///home/catad83/node_modules/@indigo-labs/dexter/build/dex/wingriders.js:115
        const swapOutNumerator = swapInAmount * reserveOut * poolFeeModifier;
                                              ^

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at WingRiders.estimatedReceive (file:///home/catad83/node_modules/@indigo-labs/dexter/build/dex/wingriders.js:115:47)
    at SwapRequest.getEstimatedReceive (file:///home/node_modules/@indigo-labs/dexter/build/requests/swap-request.js:107:68)
    at SwapRequest.getMinimumReceive (file:///home/catad83/node_modules/@indigo-labs/dexter/build/requests/swap-request.js:110:46)
    at SwapRequest.getPaymentsToAddresses (file:///home/catad83/node_modules/@indigo-labs/dexter/build/requests/swap-request.js:148:50)
    at SwapRequest.submit (file:///home/catad83/node_modules/@indigo-labs/dexter/build/requests/swap-request.js:168:14)
    at runBot (file:///home/catad83/production/bot.js:421:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Thrown at:
    at estimatedReceive (file:///home/catad83/node_modules/@indigo-labs/dexter/build/dex/wingriders.js:115:47)
    at getEstimatedReceive (file:///home/catad83/node_modules/@indigo-labs/dexter/build/requests/swap-request.js:107:68)
    at getMinimumReceive (file:///home/catad83/node_modules/@indigo-labs/dexter/build/requests/swap-request.js:110:46)
    at getPaymentsToAddresses (file:///home/catad83/node_modules/@indigo-labs/dexter/build/requests/swap-request.js:148:50)
    at submit (file:///home/catad83/node_modules/@indigo-labs/dexter/build/requests/swap-request.js:168:14)
    at runBot (file:///home/catad83/production/bot.js:421:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.0

These are the arguments calling the swap with, from a trace:

outPool is: LiquidityPool 	{
							  identifier: '',
							  poolFeePercent: 0.35,
							  extra: {},
							  dex: 'WingRiders',
							  assetA: 'lovelace',
							  assetB: Asset {
								policyId: 'dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb',
								nameHex: '0014df1047454e53',
								decimals: 0
							  },
							  reserveA: 41430452927n,
							  reserveB: 51824311338n,
							  address: 'addr1z8nvjzjeydcn4atcd93aac8allvrpjn7pjr2qsweukpnayf9eea0hzqqmpthdx6a549h44qzkua3066hggf08xvtg44s2qz7al',
							  marketOrderAddress: 'addr1wxr2a8htmzuhj39y2gq7ftkpxv98y2g67tg8zezthgq4jkg0a4ul4',
							  limitOrderAddress: 'addr1wxr2a8htmzuhj39y2gq7ftkpxv98y2g67tg8zezthgq4jkg0a4ul4',
							  lpToken: Asset {
								policyId: '026a18d04a0c642759bb3d83b12e3344894e5c1c7b2aeb1a2113a570',
								nameHex: '84eaa43491009c3a9f4e257370352e84ea7246ee8a27d9d3d9e458141d9bcf97',
								decimals: 0
							  }
							} 

_token: Asset 
		{
		  policyId: 'dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb',
		  nameHex: '0014df1047454e53',
		  decimals: 6
		} 

_tokenAmount is bigint: 324203162

**Comment by catad83** [comment]
Mentioning that I'm not using Dexter with a data provider, just with dex api

const dexter: Dexter =  (new Dexter(dexterConfig, requestConfig)).withWalletProvider( walletProvider );

**Comment by catad83** [comment]
Nevermind ... somehow _tokenAmount was not bigint
